name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo cmake . && sudo make
        
    - name: Build
      run: |
        g++ -std=c++17 -o program.out Lab2Var5.cpp  -pthread
        ./program.out
